version: 1
name: PCForge Website
type: web
plan: free

services:
  - type: web
    name: pcforge
    runtime: static
    repo: https://github.com/vaultstreamcompany-hub/pcforge
    branch: main
    rootDir: .
    buildCommand: ""
    staticPublishPath: "."
    autoDeploy: true
