version: 1

services:
  - type: web
    name: pcforge
    runtime: static
    repo: https://github.com/vaultstreamcompany-hub/pcforge
    branch: main
    rootDir: .
    buildCommand: ""
    staticPublishPath: "."
    autoDeploy: true
